baseURL = 'https://sustainabledh.org/'
locale = 'en-us'
title = 'Sustainable DH'
theme = 'rrchnm-hugo'
pluralizeListTitles = false

[params]
description = 'Documentation and resources for sustaining digital humanities projects, from the Roy Rosenzweig Center for History and New Media.'
footer = 'This work is licensed under a [Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License](https://creativecommons.org/licenses/by-nc-sa/4.0/). Cite as CC-BY-NC-SA 4.0 Roy Rosenzweig Center for History and New Media.'
matomo_site_id = 70

[[menus.main]]
name = 'Reusable Protocols'
pageRef = '/protocols'
weight = 10

[[menus.main]]
name = 'Resources'
pageRef = '/resources'
weight = 30

[[menus.main]]
name = 'About'
pageRef = '/about'
weight = 40

[[menus.main]]
name = 'True Stories'
pageRef = '/blog'
weight = 20

[[menus.footer]]
name = 'About'
pageRef = '/about'
weight = 10

[[menus.footer]]
name = 'Blog Feed (RSS)'
url = '/blog/index.xml'
weight = 20

[[menus.footer]]
name = 'Accessibility'
url = 'https://rrchnm.org/accessibility/'
weight = 30

[taxonomies]
author = 'authors'
category = 'categories'
tag = 'tags'
