baseURL = 'https://sustainabledh.org/'
languageCode = 'en-us'
title = 'Sustainble DH'
theme = "hugo-theme-monochrome"

[params]
footer = "This work is licensed under a Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License. Cite as CC-BY-NC-SA 4.0 Roy Rosenzweig Center for History and New Media"
enable_toc = true
toc_position = "right"
enable_collapsible_toc = false
enable_collapsible_changelogs = false
hide_navbar_on_scroll = true
enable_site_search = true

[[menu.navbar]]
identifier = "blog"
name = "Blog"
url = "/blog/"
weight = 110

[[menu.navbar]]
identifier = "about"
name = "About"
title = "about"
url = "/about/"
weight = 100

[[menu.navbar]]
identifier = "resources"
name = "Resources"
url = "/resources/"
weight = 70

[[menu.navbar]]
identifier = "protocols"
name = "Reusable Protocols"
url = "/reusable-protocols/"
weight = 60

[taxonomies]
category = "categories"
tag = "tags"

[outputs]
home = ["HTML", "RSS", "JSON"]
